# torchtitan Config.toml
# NOTE: this toml config is a preset for 64 A100 GPUs.

[dropping]
drop_freq = 10
num_each = 2
sim_threshold = 0.97
dataset = "c4_test"  # supported datasets: c4_test (2K), c4 (177M)
batch_size = 1
seq_len = 1024
macro_steps = 10


[job]
dump_folder = "./outputs_llama3_3b_profiling"
description = "Llama 3 3B training"

[profiling]
enable_profiling = true
save_traces_folder = "profile_trace"
profile_freq = 100

[metrics]
log_freq = 1
enable_tensorboard = true
save_tb_folder = "tb"
enable_wandb = true

[model]
name = "dynamic_llama3"
flavor = "3B_dynamic_debug"
norm_type = "rmsnorm"  # layernorm / np_layernorm / rmsnorm
tokenizer_path = "./tests/assets/test_tiktoken.model"

[optimizer]
name = "AdamW"
lr = 3e-4

[training]
batch_size = 4 # macro_batch
seq_len = 16384
warmup_steps = 20  # lr scheduler warm up
max_norm = 1.0  # grad norm clipping
steps = 100
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1
tensor_parallel_degree = 1
compile = false
dataset = "fineweb_edu"
gradient_accumulation_steps = 1 # 8 * 16 * 4 = 512

[experimental]
context_parallel_degree = 1
pipeline_parallel_degree = 1

[checkpoint]
enable_checkpoint = true
folder = "checkpoint"
interval_type = "steps"
interval = 10
model_weights_only = false
export_dtype = "float32"
async_mode = "disabled" # ["disabled", "async", "async_with_pinned_mem"]

[activation_checkpoint]
mode = 'selective'  # ['none', 'selective', 'full']
selective_ac_option = 'op'  # 'int' = ac every positive int layer or 'op', ac based on ops policy

[float8]
enable_float8_linear = false
